name: Deploy to AWS
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: "18"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Create production env file
        run: |
          cat << EOF > .env.production
          AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
          AWS_CLOUDFRONT_ID=${{ secrets.AWS_CLOUDFRONT_ID }}
          AWS_REGION=${{ env.AWS_REGION }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SOCKET_URL=${{ secrets.SOCKET_URL }}
          EOF

      - name: Build application
        run: npm run build:prod

      - name: Deploy to AWS
        run: npm run deploy
